
class ReadMeFormatStrings:
    project='\n'.join([
        "# {}",
        "",
        "## Description",
        "",
        "A brief description of your project. What problem does it solve? Who is this project for?",
        "",
        "## Getting Started",
        "",
        "### Dependencies",
        "",
        "List any dependencies or prerequisites that must be installed before using the project.",
        "",
        "### Installing",
        "",
        "Provide step-by-step instructions on how to install and set up your project locally. Include code examples if necessary.",
        "",
        "### Executing program",
        "",
        "Explain how to run the project, including any command-line arguments or configuration settings that may be required.",
        "",
        "## Help",
        "",
        "If you need help with this project, please open an issue on GitHub or contact us directly at [your email address].",
        "",
        "## Authors",
        "",
        "List the authors of the project and their GitHub usernames if applicable.",
        "",
        "## Version History",
        "",
        "* 0.0.0",
        "    * Initial Release",
    ])
    package_summary='\n'.join([
        "# template_package ",
        " - This is a template package for rapid prototyping and development. It provides a basic structure for creating Python packages with ease, including support for versioning, documentation, and testing.",
        "",
        "## my_module.py",
        "",
        "- This module defines a class `MyModule` with methods to retrieve version information and represent the object as a string. ",
        "- The `get_version_info()` method returns a formatted string containing the class name, package name, author's name, and version number. ",
        "- Finally, the `main()` function prints the version information and an example of how to initialize the `MyModule` class using the `repr()` function.",
    ])
    app='# {}'

class PoetryFormatStrings:
    base = '\n'.join([
        '[tool.poetry]',
        'name = "{}"',
        'version = "0.0.0"',
        'authors=["{}"]',
        'description="The {} package is too generic and meta for description."',
        'readme = {}',
        '',
        'packages = [',
        '    {}',
        ']',
        '',
        '[tool.poetry.dependencies]',
        'python = "^3.13,<3.14"',
        '',
        '{}',
        '',
        '{}',
    ])